/*******************************************************************************
  HTTP Application callback source file


  File Name:
   http_print.c

  Summary
    HTTP Application callback source file

  Description: 
   Provides callback headers and resolution for user's custom
   HTTP Application.
   
   This file is automatically generated by the MPFS Utility
   ALL MODIFICATIONS WILL BE OVERWRITTEN BY THE MPFS GENERATOR
   
*********************************************************************/

//DOM-IGNORE-BEGIN
/*******************************************************************************
Copyright (C) 2020 released Microchip Technology Inc.  All rights reserved.

Microchip licenses to you the right to use, modify, copy and distribute
Software only when embedded on a Microchip microcontroller or digital signal
controller that is integrated into your product or third party product
(pursuant to the sublicense terms in the accompanying license agreement).

You should refer to the license agreement accompanying this Software for
additional information regarding your rights and obligations.

SOFTWARE AND DOCUMENTATION ARE PROVIDED AS IS WITHOUT WARRANTY OF ANY KIND,
EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF
MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE.
IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR OBLIGATED UNDER
CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION, BREACH OF WARRANTY, OR
OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT DAMAGES OR EXPENSES
INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL, INDIRECT, PUNITIVE OR
CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA, COST OF PROCUREMENT OF
SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY CLAIMS BY THIRD PARTIES
(INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF), OR OTHER SIMILAR COSTS.
 *******************************************************************************/
//DOM-IGNORE-END
#include "tcpip/tcpip.h"

void TCPIP_HTTP_Print(HTTP_CONN_HANDLE connHandle,uint32_t callbackID);
void TCPIP_HTTP_Print_hellomsg(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_cookiename(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_cookiefav(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_myVariable(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_builddate(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_led(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_version(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_btn(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_pot(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_uploadedmd5(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_snmp_en(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_read_comm(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_write_comm(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_status_fail(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_mac(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_hostname(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_dhcpchecked(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_ip(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_gw(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_subnet(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_dns1(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_dns2(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_reboot(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_rebootaddr(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_status_ok(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_smtps_en(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_ddns_status(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_ddns_status_msg(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_ddns_service(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_ddns_user(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_ddns_pass(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_ddns_host(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_countrycode(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_config_stassid(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_stapwd(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_stachannel(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_apssid(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_appwd(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_apchannel(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_devmode(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_config_saveconfig(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_config_staauth(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_config_autoconnect(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_config_apauth(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_config_ssidv(HTTP_CONN_HANDLE connHandle,uint16_t);

void TCPIP_HTTP_Print(HTTP_CONN_HANDLE connHandle,uint32_t callbackID)
{
    TCP_SOCKET sktHTTP; 
    switch(callbackID)
    {
        case 0x00000000:
			TCPIP_HTTP_FileInclude(connHandle,(const uint8_t *)"header.inc");
			break;
        case 0x00000001:
			TCPIP_HTTP_Print_hellomsg(connHandle);
			break;
        case 0x00000002:
			TCPIP_HTTP_FileInclude(connHandle,(const uint8_t *)"footer.inc");
			break;
        case 0x00000003:
			TCPIP_HTTP_Print_cookiename(connHandle);
			break;
        case 0x00000004:
			TCPIP_HTTP_Print_cookiefav(connHandle);
			break;
        case 0x00000005:
			TCPIP_HTTP_Print_myVariable(connHandle);
			break;
        case 0x00000006:
			TCPIP_HTTP_Print_builddate(connHandle);
			break;
        case 0x00000007:
			TCPIP_HTTP_Print_led(connHandle,2);
			break;
        case 0x00000008:
			TCPIP_HTTP_Print_led(connHandle,1);
			break;
        case 0x0000000d:
			TCPIP_HTTP_Print_version(connHandle);
			break;
        case 0x0000000e:
			TCPIP_HTTP_Print_led(connHandle,0);
			break;
        case 0x0000000f:
			TCPIP_HTTP_Print_btn(connHandle,0);
			break;
        case 0x00000010:
			TCPIP_HTTP_Print_btn(connHandle,1);
			break;
        case 0x00000011:
			TCPIP_HTTP_Print_btn(connHandle,2);
			break;
        case 0x00000012:
			TCPIP_HTTP_Print_pot(connHandle);
			break;
        case 0x00000013:
			TCPIP_HTTP_Print_uploadedmd5(connHandle);
			break;
        case 0x00000014:
			TCPIP_HTTP_Print_snmp_en(connHandle);
			break;
        case 0x00000015:
			TCPIP_HTTP_Print_read_comm(connHandle,0);
			break;
        case 0x00000016:
			TCPIP_HTTP_Print_read_comm(connHandle,1);
			break;
        case 0x00000017:
			TCPIP_HTTP_Print_read_comm(connHandle,2);
			break;
        case 0x00000018:
			TCPIP_HTTP_Print_write_comm(connHandle,0);
			break;
        case 0x00000019:
			TCPIP_HTTP_Print_write_comm(connHandle,1);
			break;
        case 0x0000001a:
			TCPIP_HTTP_Print_write_comm(connHandle,2);
			break;
        case 0x0000001b:
			TCPIP_HTTP_Print_status_fail(connHandle);
			break;
        case 0x0000001c:
			TCPIP_HTTP_Print_config_mac(connHandle);
			break;
        case 0x0000001d:
			TCPIP_HTTP_Print_config_hostname(connHandle);
			break;
        case 0x0000001e:
			TCPIP_HTTP_Print_config_dhcpchecked(connHandle);
			break;
        case 0x0000001f:
			TCPIP_HTTP_Print_config_ip(connHandle);
			break;
        case 0x00000020:
			TCPIP_HTTP_Print_config_gw(connHandle);
			break;
        case 0x00000021:
			TCPIP_HTTP_Print_config_subnet(connHandle);
			break;
        case 0x00000022:
			TCPIP_HTTP_Print_config_dns1(connHandle);
			break;
        case 0x00000023:
			TCPIP_HTTP_Print_config_dns2(connHandle);
			break;
        case 0x00000024:
			TCPIP_HTTP_Print_reboot(connHandle);
			break;
        case 0x00000025:
			TCPIP_HTTP_Print_rebootaddr(connHandle);
			break;
        case 0x00000026:
			TCPIP_HTTP_Print_status_ok(connHandle);
			break;
        case 0x00000027:
			TCPIP_HTTP_Print_smtps_en(connHandle);
			break;
        case 0x00000028:
			TCPIP_HTTP_Print_ddns_status(connHandle);
			break;
        case 0x00000029:
			TCPIP_HTTP_Print_ddns_status_msg(connHandle);
			break;
        case 0x0000002a:
			TCPIP_HTTP_Print_ddns_service(connHandle,0);
			break;
        case 0x0000002b:
			TCPIP_HTTP_Print_ddns_service(connHandle,1);
			break;
        case 0x0000002c:
			TCPIP_HTTP_Print_ddns_service(connHandle,2);
			break;
        case 0x0000002d:
			TCPIP_HTTP_Print_ddns_user(connHandle);
			break;
        case 0x0000002e:
			TCPIP_HTTP_Print_ddns_pass(connHandle);
			break;
        case 0x0000002f:
			TCPIP_HTTP_Print_ddns_host(connHandle);
			break;
        case 0x00000033:
			TCPIP_HTTP_Print_config_countrycode(connHandle,0);
			break;
        case 0x00000034:
			TCPIP_HTTP_Print_config_countrycode(connHandle,1);
			break;
        case 0x00000035:
			TCPIP_HTTP_Print_config_countrycode(connHandle,2);
			break;
        case 0x00000036:
			TCPIP_HTTP_Print_config_countrycode(connHandle,3);
			break;
        case 0x00000040:
			TCPIP_HTTP_Print_config_stassid(connHandle);
			break;
        case 0x00000041:
			TCPIP_HTTP_Print_config_stapwd(connHandle);
			break;
        case 0x00000043:
			TCPIP_HTTP_Print_config_stachannel(connHandle);
			break;
        case 0x00000045:
			TCPIP_HTTP_Print_config_apssid(connHandle);
			break;
        case 0x00000046:
			TCPIP_HTTP_Print_config_appwd(connHandle);
			break;
        case 0x00000048:
			TCPIP_HTTP_Print_config_apchannel(connHandle);
			break;
        case 0x00000049:
			TCPIP_HTTP_Print_config_devmode(connHandle,0);
			break;
        case 0x0000004a:
			TCPIP_HTTP_Print_config_devmode(connHandle,1);
			break;
        case 0x0000004d:
			TCPIP_HTTP_Print_config_saveconfig(connHandle,0);
			break;
        case 0x0000004e:
			TCPIP_HTTP_Print_config_saveconfig(connHandle,1);
			break;
        case 0x00000050:
			TCPIP_HTTP_Print_config_staauth(connHandle,1);
			break;
        case 0x00000052:
			TCPIP_HTTP_Print_config_staauth(connHandle,3);
			break;
        case 0x00000053:
			TCPIP_HTTP_Print_config_autoconnect(connHandle,0);
			break;
        case 0x00000054:
			TCPIP_HTTP_Print_config_autoconnect(connHandle,1);
			break;
        case 0x00000056:
			TCPIP_HTTP_Print_config_apauth(connHandle,1);
			break;
        case 0x00000058:
			TCPIP_HTTP_Print_config_apauth(connHandle,3);
			break;
        case 0x00000059:
			TCPIP_HTTP_Print_config_ssidv(connHandle,0);
			break;
        case 0x0000005a:
			TCPIP_HTTP_Print_config_ssidv(connHandle,1);
			break;
        case 0x0000005b:
			TCPIP_HTTP_Print_config_apauth(connHandle,5);
			break;
        case 0x0000005c:
			TCPIP_HTTP_Print_config_apauth(connHandle,6);
			break;
        case 0x0000005d:
			TCPIP_HTTP_Print_config_staauth(connHandle,5);
			break;
        case 0x0000005e:
			TCPIP_HTTP_Print_config_staauth(connHandle,6);
			break;
        case 0x0000005f:
			TCPIP_HTTP_Print_config_apauth(connHandle,4);
			break;
        default:
            // Output notification for undefined values
            sktHTTP = TCPIP_HTTP_CurrentConnectionSocketGet(connHandle);
            TCPIP_TCP_ArrayPut(sktHTTP, (const uint8_t *)"!DEF", 4);
    }
    return;
}

void TCPIP_HTTP_Print_myVariable(HTTP_CONN_HANDLE connHandle)
{
    TCP_SOCKET sktHTTP = TCPIP_HTTP_CurrentConnectionSocketGet(connHandle);
    TCPIP_TCP_Put(sktHTTP, '~');
    return;
}
